name: Build and Upload Artifact

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest
        run: pytest

      - name: Package code as artifact
        run: |
          mkdir -p output
          cp -r your_model_or_code_folder output/
          zip -r artifact.zip output/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifact.zip
